## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "multiPhysicsFoam - Documentation"
theme = "docsy"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
canonifyURLs = "true"

# Remote
baseURL = "https://cohabes.github.io/multiPhysicsFoamDocs/"
publishDir = "docs"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]