baseURL = 'https://cohabes.github.io/multiPhysicsFoamDocs/'
relativeURLs = true
canonifyURLs = true
languageCode = 'en-us'
title = 'multiPhysicsFoam - Documentation'
theme = "docsy"
publishDir = "docs"
